// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXsQVgem1b9y-d4i9P925lTEBLmYjRajo',
    appId: '1:104562992285:web:7f579ebeb840a02b532074',
    messagingSenderId: '104562992285',
    projectId: 'crypto-wallet-5afc6',
    authDomain: 'crypto-wallet-5afc6.firebaseapp.com',
    storageBucket: 'crypto-wallet-5afc6.appspot.com',
    measurementId: 'G-WK8F8BPVQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNbSa82rh0Ijp876LS94Lz6qDa_FLqJKc',
    appId: '1:104562992285:android:6e0aa3c2cb25dcaa532074',
    messagingSenderId: '104562992285',
    projectId: 'crypto-wallet-5afc6',
    storageBucket: 'crypto-wallet-5afc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMf3tgLx9B9dYtElH_nghOiVtGv-lOYas',
    appId: '1:104562992285:ios:a162018e56aa9869532074',
    messagingSenderId: '104562992285',
    projectId: 'crypto-wallet-5afc6',
    storageBucket: 'crypto-wallet-5afc6.appspot.com',
    iosClientId: '104562992285-88b2o5fh2uhb5jgq12bo3b1h21t3o0up.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMf3tgLx9B9dYtElH_nghOiVtGv-lOYas',
    appId: '1:104562992285:ios:a162018e56aa9869532074',
    messagingSenderId: '104562992285',
    projectId: 'crypto-wallet-5afc6',
    storageBucket: 'crypto-wallet-5afc6.appspot.com',
    iosClientId: '104562992285-88b2o5fh2uhb5jgq12bo3b1h21t3o0up.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoWallet',
  );
}
